"""
This module implements the analytical gradient as defined in the paper:
'Practical Optimization for hybrid quantum-classical algorithms'
Compute the analytical gradient for the qaoa algorithm.
"""


import numpy as np
import pyquil.quil as pq
import pyquil.api as api
from pyquil.gates import *
from pyquil.paulis import *

import maxcut_qaoa_core


def generate_make_controlled(ancilla_qubit_index):
    """
    Creates a function which maps operators to controlled operators
    :param (int) ancilla_qubit_index: controls the controlled gates
    :return (function) make_controlled: maps gates to controlled gates
    """

    def make_controlled(pauli_operator):
        """
        Maps Pauli operators to the corresponding controlled gate
        :param (pauli_op) pauli_operator: a qubit_index, and gate_name pair
        :return (Gate) mapped_gate: the corresponding controlled gate
        """
        qubit_index, gate_name = pauli_operator
        mapping_dict = {
            "X": CNOT,
            "Z": CPHASE(np.pi)
            }
        mapped_gate_op = mapping_dict[gate_name]
        qubit_indices = [ancilla_qubit_index, qubit_index]
        mapped_gate = mapped_gate_op(*qubit_indices)
        return mapped_gate

    return make_controlled

def pauli_term_to_program(pauli_term, pauli_operator_mapping):
    """
    Converts a PauliTerm to the corresponding list of Gates
    :param (PauliTerm) pauli_term: has a list of pauli operators
    :param (function) operator_mapping: e.g. make_controlled
    :return (list[Gate]) program: lookup each gate in the STANDARD_GATES dict
    """
    program = pq.Program()
    for pauli_operator in pauli_term:
        mapped_gate = pauli_operator_mapping(pauli_operator)
        program.inst(mapped_gate)
    return program

def hamiltonian_to_programs(hamiltonian, pauli_operator_mapping):
    """
    Converts a hamiltonian to the corresponding list of programs
    :param (PauliSum) hamiltonian: has a list of pauli terms
    :return (list[pq.Program]) programs: the programs from the hamiltonian
    """
    programs = [pauli_term_to_program(pauli_term, pauli_operator_mapping)
        for pauli_term in hamiltonian]
    return programs

def get_analytical_derivative_program(unitary, generator,
        pauli_operator_mapping):
    """
    Writes the analytical derivative of a unitary
    :param (pq.Program) unitary: the unitary generated by generator
    :param (PauliSum) generator: to be converted into list[pq.Program]
    :return (list[pq.Program]) analytical_derivative: the derivative programs
    """
    programs = hamiltonian_to_programs(generator, pauli_operator_mapping)
    analytical_derivative_programs = [program + unitary for program in programs]
    return analytical_derivative_programs

def unitaries_list_to_analytical_derivatives_list(step_index, hamiltonian,
        unitaries_list, make_controlled):
    """
    Computes the analytical derivative of a unitary in a list of unitaries
    :param (int) step_index: the index of selected unitary in the list
    :param (PauliSum) hamiltonian: the hamiltonian which generates the unitaries
    :param (list[pq.Program()]) unitaries_list: the generated unitaries
    :param (function) make controlled: Maps Pauli operators to controlled gates
    :return (list[list[pq.Program()]]): the derivative terms for a given step
    """
    unitaries_before = unitaries_list[:step_index]
    unitary_term = unitaries_list[step_index]
    unitaries_after = unitaries_list[step_index:]
    analytical_derivative_programs = get_analytical_derivative_programs(
        unitary_term, hamiltonian, make_controlled)
    unitaries_list_analytical_derivatives_programs = []
    for analytical_derivative_program in analytical_derivative_programs:
        unitaries_list_analytical_derivative_program = (
            unitaries_after + analytical_derivative_term + unitaries_before)
        unitaries_list_analytical_derivative_programs.append(
            unitaries_list_analytical_derivative_program)
    return unitaries_list_analytical_derivative_programs


def generate_analytical_derivative_map(unitaries_lists, hamiltonians,
        make_controlled):
    """
    Generates a map which
    """
    assert len(unitaries_lists) == len(hamiltonians)

    def analytical_derivative_map(step_index):
        ham_indices = xrange(len(hamiltonians)
        combined_analytical_derivatives = []
        for ham_index in ham_indices:
            other_ham_indices = [_idx for _idx in indices if _idx != ham_index]
            this_hamiltonian = hamiltonians[ham_index]
            this_unitaries_list = unitaries_lists[ham_index]
            analytical_derivatives_list = \
                unitaries_list_to_analytical_derivatives_list(step_index,
                this_hamiltonian, this_unitaries_list, make_controlled)
            for other_ham_index in other_ham_indices:
                other_unitaries_list = unitaries_list[other_ham_index]
                combined other_unitaries_list + analytical_derivatives_list



    return analytical_gradient_finder

def compute_qaoa_analytical_derivative(cost_unitary_list, driver_unitary_list,
    make_controlled)


#Reduce the complexity!
def insert_ancilla_controlled_hermitian(gradient_component_programs,
        hermitian_structure, hamiltonian_type, ancilla_qubit_index):
    gradient_component_hermitian_operators = hermitian_structure[
        step_index][hamiltonian_type]
    new_gradient_component_programs = []
    for op_type, gate in gradient_component_hermitian_operators:
        operator_name = gate.operator_name
        controlled_operator = make_controlled(operator_name)
        qubit_index = gate.arguments[0]
        controlled_gate = controlled_operator(ancilla_qubit_index, qubit_index)
        if hamiltonian_type == "driver":
            new_gradient_component_programs.append(gradient_component_programs[0] +
                                                   controlled_gate)
        if hamiltonian_type == "cost":
            gradient_component_programs[0].inst(controlled_gate)
            new_gradient_component_programs = gradient_component_programs
    return new_gradient_component_programs


#Reduce the complexity!
def get_analytical_gradient_component_qaoa(params,
        reference_state_program, num_qubits, step_index, hamiltonian_type):
    """
    Computes a single component of the analytical gradient
    """
    gradient_component_programs = [reference_state_program]
    unitary_program, unitary_structure, hermitian_structure = \
        program_parameterizer(params)
    ancilla_qubit_index = num_qubits
    for gradient_component_program in gradient_component_programs:
        gradient_component_program.inst(H(ancilla_qubit_index))

    for free_step_index in unitary_structure:
        step_unitary_structure = unitary_structure[free_step_index]
        for free_hamiltonian_type in step_unitary_structure:

            if (free_step_index == step_index and
                    free_hamiltonian_type == hamiltonian_type):
                gradient_component_programs = insert_ancilla_controlled_hermitian(
                    gradient_component_programs, hermitian_structure,
                    hamiltonian_type, ancilla_qubit_index)

            hamiltonian_operators = step_unitary_structure[free_hamiltonian_type]
            for op_type, gate in hamiltonian_operators:
                for gradient_component_program in gradient_component_programs:
                    gradient_component_program.inst(gate)

    for gradient_component_program in gradient_component_programs:
        gradient_component_program.inst(S(ancilla_qubit_index))
        gradient_component_program.inst(H(ancilla_qubit_index))
    return gradient_component_programs

def extend_cost_hamiltonian(cost_hamiltonian, ancilla_qubit_index):
    ancilla_qubit_term = PauliTerm("Z", ancilla_qubit_index)
    full_cost_hamiltonian = cost_hamiltonian*ancilla_qubit_term
    return full_cost_hamiltonian
